services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    command:
      - --configFile=/etc/traefik/traefik.yml
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - traefik_letsencrypt:/letsencrypt
      - ./traefik/logs:/logs
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - traefik_net

  bot:
    image: ivanskrb21/vinaslt_bot:latest
    container_name: telegram_bot
    command: ["python3", "main.py"]
    entrypoint: ["/app/entrypoint.sh"]
    environment:
      - API_SERVICE_URL=http://api_service:8000/
      - PAYMENT_SERVICE_URL=http://payment_service:8002/
      - CARFAX_SERVICE_URL=http://carfax_service:8001/
    depends_on:
      - postgres_bot
      - api_service
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - telegram_bot_net
      - internal_net

  api_service:
    image: ivanskrb21/vinaslt_api_service:latest
    container_name: api_service
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--log-level", "debug"]
    env_file:
      - .env
    expose:
      - "8000"
    environment:
      - REDIS_URL=redis://redis_api_service:${API_REDIS_PORT}/0
    networks:
      - api-net
      - internal_net

  redis_api_service:
    image: redis:7
    container_name: redis_api_service
    ports:
      - "${API_REDIS_PORT}:6379"
    volumes:
      - redis_api_data:/data
    restart: unless-stopped
    networks:
      - api-net

  postgres_bot:
    image: postgres:15
    container_name: postgres_bot
    environment:
      - POSTGRES_USER=${BOT_DB_USER}
      - POSTGRES_PASSWORD=${BOT_DB_PASS}
      - POSTGRES_DB=${BOT_DB_NAME}
    volumes:
      - pg_data_bot:/var/lib/postgresql/data
    networks:
      - telegram_bot_net

  carfax_service:
    image: ivanskrb21/vinaslt_carfax_service:latest
    container_name: carfax_service
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8001", "--log-level", "debug"]
    entrypoint: ["/app/entrypoint.sh"]
    env_file:
      - .env
    expose:
      - "8001"
    networks:
      - carfax_service_net
      - internal_net

  postgres_carfax:
    image: postgres:15
    container_name: postgres_carfax
    environment:
      - POSTGRES_USER=${CARFAX_DB_USER}
      - POSTGRES_PASSWORD=${CARFAX_DB_PASS}
      - POSTGRES_DB=${CARFAX_DB_NAME}
    ports:
      - '5432:5432'
    volumes:
      - pg_data_carfax:/var/lib/postgresql/data
    networks:
      - carfax_service_net

  payment_service:
    image: ivanskrb21/vinaslt_payment_service:latest
    container_name: payment_service
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8002", "--log-level", "debug"]
    entrypoint: ["/app/entrypoint.sh"]
    env_file:
      - .env
    expose:
      - "8002"
    environment:
      - CARFAX_SERVICE_URL=http://carfax_service:8001/
    networks:
      - payment_service_net
      - internal_net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.payment.rule=Host(`api.vinas.lt`) && PathPrefixStrip(`/payment`)"
      - "traefik.http.routers.payment.entrypoints=websecure"
      - "traefik.http.routers.payment.tls.certresolver=letsencrypt"
      - "traefik.http.services.payment.loadbalancer.server.port=8002"

  postgres_payment:
    image: postgres:15
    container_name: postgres_payment
    environment:
      - POSTGRES_USER=${PAYMENT_DB_USER}
      - POSTGRES_PASSWORD=${PAYMENT_DB_PASS}
      - POSTGRES_DB=${PAYMENT_DB_NAME}
    volumes:
      - pg_data_payment:/var/lib/postgresql/data
    networks:
      - payment_service_net

volumes:
  pg_data_bot:
  pg_data_carfax:
  pg_data_payment:
  redis_api_data:
  traefik_letsencrypt:
    driver: local

networks:
  telegram_bot_net:
  carfax_service_net:
  payment_service_net:
  api-net:
  internal_net:
  traefik_net:
