log:
  level: DEBUG
  filePath: /logs/traefik.log

accessLog:
  filePath: /logs/access.log

api:
  dashboard: true        # insecure=true только во время отладки

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  docker:
    exposedByDefault: false
    network: traefik_net

certificatesResolvers:
  letsencrypt:
    acme:
      email: peyrovskaaa@gmail.com
      storage: /letsencrypt/acme.json
      httpChallenge:
        entryPoint: web
