log:
  level: DEBUG
  filePath: /logs/traefik.log

accessLog:
  filePath: /logs/access.log

api:
  dashboard: true
  insecure: false  # только для отладки! (позволяет доступ без HTTPS)

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  docker:
    exposedByDefault: false

certificatesResolvers:
  letsencrypt:
    acme:
      email: peyrovskaaa@gmail.com
      storage: /letsencrypt/acme.json
      httpChallenge:
        entryPoint: web
